from pathlib import Path

path = Path('gui_maszyny.py')
text = path.read_text(encoding='utf-8')


def replace_once(old: str, new: str, label: str) -> None:
    global text
    count = text.count(old)
    if count != 1:
        raise SystemExit(f'{label}: expected exactly 1 match, got {count}')
    text = text.replace(old, new, 1)


replace_once(
    '# version: 1.1\n# Zmiany 1.1:\n',
    '# version: 1.2\n# Zmiany 1.2:\n'
    '# - Uproszczono okno Użytkowanie maszyny: mniej kolumn w historii i serwisach.\n'
    '# - Historia statusów pokazuje bezpośrednio powód / zdarzenie serwisowe.\n'
    '# - Historia statusów odświeża się od razu po rozpoczęciu i zakończeniu serwisu.\n'
    '# Zmiany 1.1:\n',
    'version header',
)

old_history = '''        hist_cols = (\n            "status", "start", "stop", "czas", "kto", "zdjecia", "opis"\n        )\n        hist_tree = ttk.Treeview(\n            history_box, columns=hist_cols, show="headings", height=12\n        )\n        hist_setup = {\n            "status": ("Status", 150, "w"),\n            "start": ("Start", 140, "center"),\n            "stop": ("Stop", 140, "center"),\n            "czas": ("Czas", 110, "center"),\n            "kto": ("Kto", 110, "w"),\n            "zdjecia": ("Zdjęcia", 80, "center"),\n            "opis": ("Opis", 420, "w"),\n        }\n'''
new_history = '''        hist_cols = ("status", "start", "stop", "kto", "zdarzenie")\n        hist_tree = ttk.Treeview(\n            history_box, columns=hist_cols, show="headings", height=9\n        )\n        hist_setup = {\n            "status": ("Status", 135, "w"),\n            "start": ("Start", 125, "center"),\n            "stop": ("Stop", 125, "center"),\n            "kto": ("Kto", 120, "w"),\n            "zdarzenie": ("Powód / zdarzenie", 430, "w"),\n        }\n'''
replace_once(old_history, new_history, 'history columns')

old_values = '''        def _history_entry_values(item: Dict[str, Any]) -> tuple:\n            status = _machine_status_label(item.get("status"))\n            start = str(item.get("started_at") or "—").replace("T", " ")[:16]\n            if item.get("__current"):\n                stop = "w toku"\n                duration = _format_duration_minutes(\n                    _duration_minutes(item.get("started_at"), _machine_now_iso())\n                )\n                who = str(item.get("changed_by") or "—")\n                note = str(item.get("note") or "")\n            else:\n                stop = str(item.get("ended_at") or "—").replace("T", " ")[:16]\n                duration = _format_duration_minutes(item.get("duration_minutes"))\n                who = str(item.get("closed_by") or item.get("changed_by") or "—")\n                note = str(item.get("close_note") or item.get("note") or "")\n            photos = (\n                item.get("photos") if isinstance(item.get("photos"), list) else []\n            )\n            photos_text = f"📷 {len(photos)}" if photos else "—"\n            return status, start, stop, duration, who, photos_text, note\n\n        entries = _history_entries_for_usage(machine)\n        if entries:\n            for item in entries:\n                iid = hist_tree.insert(\n                    "", "end", values=_history_entry_values(item)\n                )\n                history_items[iid] = item\n        else:\n            hist_tree.insert(\n                "",\n                "end",\n                values=(\n                    "—",\n                    "—",\n                    "—",\n                    "—",\n                    "—",\n                    "—",\n                    "Brak historii. Pierwszy wpis powstanie przy zmianie "\n                    "statusu.",\n                ),\n            )\n'''
new_values = '''        def _history_entry_values(item: Dict[str, Any]) -> tuple:\n            status = _machine_status_label(item.get("status"))\n            start = str(item.get("started_at") or "—").replace("T", " ")[:16]\n            if item.get("__current"):\n                stop = "w toku"\n                who = str(item.get("changed_by") or "—")\n                note = str(item.get("note") or "")\n            else:\n                stop = str(item.get("ended_at") or "—").replace("T", " ")[:16]\n                who = str(item.get("closed_by") or item.get("changed_by") or "—")\n                note = str(item.get("close_note") or item.get("note") or "")\n            photos = (\n                item.get("photos") if isinstance(item.get("photos"), list) else []\n            )\n            event_text = note.strip() or "Zmiana statusu"\n            if photos:\n                event_text += f" | zdjęcia: {len(photos)}"\n            return status, start, stop, who, event_text\n\n        def _refresh_history_tree() -> None:\n            history_items.clear()\n            for iid in hist_tree.get_children():\n                hist_tree.delete(iid)\n            entries = _history_entries_for_usage(machine)\n            if entries:\n                for item in entries:\n                    iid = hist_tree.insert(\n                        "", "end", values=_history_entry_values(item)\n                    )\n                    history_items[iid] = item\n            else:\n                hist_tree.insert(\n                    "",\n                    "end",\n                    values=(\n                        "—",\n                        "—",\n                        "—",\n                        "—",\n                        "Brak historii. Pierwszy wpis powstanie przy zmianie statusu.",\n                    ),\n                )\n\n        _refresh_history_tree()\n'''
replace_once(old_values, new_values, 'history values and refresh')

old_reviews = '''        reviews_cols = (\n            "date", "type", "status", "suggested", "done_by", "done", "desc"\n        )\n        reviews_tree = ttk.Treeview(\n            reviews_box,\n            columns=reviews_cols,\n            show="headings",\n            height=5,\n        )\n        reviews_setup = {\n            "date": ("Data", 105, "center"),\n            "type": ("Typ", 150, "w"),\n            "status": ("Status", 100, "center"),\n            "suggested": ("Sugerowani", 140, "w"),\n            "done_by": ("Wykonali", 140, "w"),\n            "done": ("Wykonano", 125, "center"),\n            "desc": ("Opis", 300, "w"),\n        }\n'''
new_reviews = '''        reviews_cols = ("date", "type", "status", "people", "details")\n        reviews_tree = ttk.Treeview(\n            reviews_box,\n            columns=reviews_cols,\n            show="headings",\n            height=6,\n        )\n        reviews_setup = {\n            "date": ("Data", 105, "center"),\n            "type": ("Typ", 165, "w"),\n            "status": ("Status", 105, "center"),\n            "people": ("Osoby", 190, "w"),\n            "details": ("Szczegóły", 420, "w"),\n        }\n'''
replace_once(old_reviews, new_reviews, 'review columns')

old_refresh = '''            for entry in _machine_reviews(machine):\n                values = (\n                    str(entry.get("planned_date") or "—"),\n                    str(entry.get("type") or ""),\n                    _review_status_label(entry.get("status")),\n                    _people_text(entry.get("suggested_workers")),\n                    _people_text(entry.get("completed_by")),\n                    str(entry.get("completed_at") or "—").replace("T", " ")[:16],\n                    str(entry.get("description") or entry.get("result_note") or ""),\n                )\n                iid = reviews_tree.insert("", "end", values=values)\n                review_items[iid] = entry\n'''
new_refresh = '''            for entry in _machine_reviews(machine):\n                status_label = _review_status_label(entry.get("status"))\n                if status_label == "Wykonany":\n                    people = _people_text(entry.get("completed_by"))\n                    completed_at = str(entry.get("completed_at") or "").replace("T", " ")[:16]\n                    details = str(entry.get("result_note") or entry.get("description") or "")\n                    if completed_at:\n                        details = f"Wykonano: {completed_at}" + (f" | {details}" if details else "")\n                elif status_label == "W trakcie":\n                    people = str(entry.get("started_by") or "") or _people_text(entry.get("suggested_workers"))\n                    started_at = str(entry.get("started_at") or "").replace("T", " ")[:16]\n                    details = str(entry.get("description") or "")\n                    if started_at:\n                        details = f"Rozpoczęto: {started_at}" + (f" | {details}" if details else "")\n                else:\n                    people = _people_text(entry.get("suggested_workers"))\n                    details = str(entry.get("description") or "")\n                values = (\n                    str(entry.get("planned_date") or "—"),\n                    str(entry.get("type") or ""),\n                    status_label,\n                    people or "—",\n                    details or "—",\n                )\n                iid = reviews_tree.insert("", "end", values=values)\n                review_items[iid] = entry\n'''
replace_once(old_refresh, new_refresh, 'review refresh')

# Both service state transitions must immediately refresh the open history table.
old_call = '''            machine.update(updated)\n            _persist_machine_after_review_change(updated)\n            _refresh_reviews_tree()\n'''
new_call = '''            machine.update(updated)\n            _persist_machine_after_review_change(updated)\n            _refresh_history_tree()\n            _refresh_reviews_tree()\n'''
count = text.count(old_call)
if count != 2:
    raise SystemExit(f'service transition refresh: expected 2 matches, got {count}')
text = text.replace(old_call, new_call)

path.write_text(text, encoding='utf-8')
