from pathlib import Path

path = Path("start.py")
text = path.read_text(encoding="utf-8")


def replace_once(old: str, new: str, label: str) -> None:
    global text
    count = text.count(old)
    if count != 1:
        raise SystemExit(f"{label}: expected 1 match, got {count}")
    text = text.replace(old, new, 1)


replace_once(
    '# version: 1.1.6\n# Moduł: start\n# Zmiany 1.1.6:\n',
    '# version: 1.1.7\n# Moduł: start\n# Zmiany 1.1.7:\n# - Lokalne dane runtime (data/, wydruki/, logs/, backup/, wm_root.json) nie blokują już aktualizacji kodu.\n# - Przy samych zmianach runtime updater używa git pull --ff-only, który bezpiecznie odmawia przy konflikcie.\n# - Lokalne zmiany plików programu nadal blokują automatyczną aktualizację.\n# Zmiany 1.1.6:\n',
    "version header",
)

replace_once(
    '''def _wm_git_check_on_start(\n    preferred_branch: str | None = None,\n    status_callback=None,\n):\n''',
    '''def _wm_git_status_paths(status_text: str) -> list[str]:\n    """Wyciągnij ścieżki z `git status --porcelain`."""\n    paths: list[str] = []\n    for raw_line in str(status_text or "").splitlines():\n        if not raw_line.strip():\n            continue\n        path_text = raw_line[3:] if len(raw_line) >= 4 else raw_line\n        if " -> " in path_text:\n            path_text = path_text.split(" -> ", 1)[-1]\n        path_text = path_text.strip().strip('"').replace("\\\\", "/")\n        if path_text:\n            paths.append(path_text)\n    return paths\n\n\ndef _wm_git_runtime_only_dirty(paths: list[str]) -> bool:\n    """True, gdy wszystkie lokalne zmiany dotyczą wyłącznie danych runtime WM."""\n    if not paths:\n        return False\n    runtime_prefixes = ("data/", "wydruki/", "logs/", "backup/")\n    runtime_files = {"wm_root.json"}\n    for value in paths:\n        normalized = str(value or "").strip().replace("\\\\", "/").lstrip("./")\n        if normalized in runtime_files:\n            continue\n        if any(normalized.startswith(prefix) for prefix in runtime_prefixes):\n            continue\n        return False\n    return True\n\n\ndef _wm_git_check_on_start(\n    preferred_branch: str | None = None,\n    status_callback=None,\n):\n''',
    "git helpers",
)

old_block = '''        if behind > 0:\n            status_proc = subprocess.run(\n                ["git", "status", "--porcelain"],\n                capture_output=True,\n                text=True,\n            )\n            if status_proc.returncode == 0 and status_proc.stdout.strip():\n                print(\n                    "[WM-DBG][GIT] skipped: local changes (commit or stash required)"\n                )\n            else:\n                print(\n                    "[WM-DBG][GIT] Wykryto nowsze commity w origin, wykonuję git pull --rebase..."\n                )\n                _status("Pobieram aktualizację WM...")\n                pull_proc = subprocess.run(\n                    ["git", "pull", "--rebase", "origin", preferred_branch],\n                    check=False,\n                )\n                if pull_proc.returncode == 0:\n                    print("[WM-DBG][GIT] Aktualizacja lokalnego repo zakończona.")\n                    _status("Aktualizacja zakończona ✓")\n                    result = "updated"\n                else:\n                    print(\n                        "[WM-DBG][GIT] git pull --rebase zakończony kodem "\n                        f"{pull_proc.returncode}."\n                    )\n                    _status("Błąd pobierania aktualizacji")\n                    result = "error"\n            if status_proc.returncode == 0 and status_proc.stdout.strip():\n                _status("Pominięto aktualizację — lokalne zmiany")\n                result = "skipped"\n        else:\n'''

new_block = '''        if behind > 0:\n            status_proc = subprocess.run(\n                ["git", "status", "--porcelain"],\n                capture_output=True,\n                text=True,\n            )\n            dirty_paths = (\n                _wm_git_status_paths(status_proc.stdout)\n                if status_proc.returncode == 0\n                else []\n            )\n            runtime_only_dirty = _wm_git_runtime_only_dirty(dirty_paths)\n\n            if dirty_paths and not runtime_only_dirty:\n                print(\n                    "[WM-DBG][GIT] skipped: local code/config changes "\n                    f"({', '.join(dirty_paths[:8])})"\n                )\n                _status("Pominięto aktualizację — zmieniony kod lokalny")\n                result = "skipped"\n            else:\n                if runtime_only_dirty:\n                    print(\n                        "[WM-DBG][GIT] Lokalne zmiany dotyczą tylko danych runtime; "\n                        "próbuję bezpiecznego git pull --ff-only."\n                    )\n                    _status("Pobieram aktualizację WM — dane lokalne zostają...")\n                    pull_cmd = [\n                        "git", "pull", "--ff-only", "origin", preferred_branch\n                    ]\n                    pull_label = "git pull --ff-only"\n                else:\n                    print(\n                        "[WM-DBG][GIT] Wykryto nowsze commity w origin, "\n                        "wykonuję git pull --rebase..."\n                    )\n                    _status("Pobieram aktualizację WM...")\n                    pull_cmd = [\n                        "git", "pull", "--rebase", "origin", preferred_branch\n                    ]\n                    pull_label = "git pull --rebase"\n\n                pull_proc = subprocess.run(pull_cmd, check=False)\n                if pull_proc.returncode == 0:\n                    print("[WM-DBG][GIT] Aktualizacja lokalnego repo zakończona.")\n                    _status("Aktualizacja zakończona ✓")\n                    result = "updated"\n                elif runtime_only_dirty:\n                    print(\n                        f"[WM-DBG][GIT] {pull_label} odmówił aktualizacji "\n                        f"(kod {pull_proc.returncode}) — lokalne dane pozostawione bez zmian."\n                    )\n                    _status("Aktualizacja zablokowana — konflikt z lokalnymi danymi")\n                    result = "blocked"\n                else:\n                    print(\n                        f"[WM-DBG][GIT] {pull_label} zakończony kodem "\n                        f"{pull_proc.returncode}."\n                    )\n                    _status("Błąd pobierania aktualizacji")\n                    result = "error"\n        else:\n'''
replace_once(old_block, new_block, "update logic")

replace_once(
    '''                    elif value == "skipped":\n                        status_var.set("Aktualizacja pominięta")\n                    else:\n                        status_var.set("Nie udało się sprawdzić aktualizacji")\n                    if value == "updated":\n                        close_delay_ms = 2500\n                    elif value == "current":\n                        close_delay_ms = 650\n                    else:\n                        close_delay_ms = 1000\n''',
    '''                    elif value == "skipped":\n                        status_var.set("Aktualizacja pominięta — zmieniony kod lokalny")\n                    elif value == "blocked":\n                        status_var.set("Aktualizacja zablokowana — konflikt z lokalnymi danymi")\n                    else:\n                        status_var.set("Nie udało się sprawdzić aktualizacji")\n                    if value == "updated":\n                        close_delay_ms = 2500\n                    elif value == "current":\n                        close_delay_ms = 650\n                    elif value in {"skipped", "blocked"}:\n                        close_delay_ms = 2200\n                    else:\n                        close_delay_ms = 1000\n''',
    "splash result",
)

path.write_text(text, encoding="utf-8")
